# Generated by Django 5.1.2 on 2024-12-11 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"ordering": ["created_at"], "verbose_name": "Блог", "verbose_name_plural": "Блоги"},
        ),
        migrations.RenameField(
            model_name="blog",
            old_name="content",
            new_name="article",
        ),
    ]
