# Generated by Django 5.1.2 on 2024-12-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("can_unpublish_blog", "Can unpublish blog"),
                    ("can_publish_blog", "Can publish blog"),
                ],
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
